"""生成 Protocol Registry 只读产物（Step 10：单一来源）。

来源：agent/executor/protocol_manifest.yaml（唯一可编辑）
产物（均为生成文件，带 DO NOT EDIT 头）：
  - backend/app/protocol/action_registry.json
  - backend/app/schemas/generated_case_params.py
  - frontend/src/api/generated/registry.ts

用法：
  uv run python scripts/generate_protocol.py                 # 写入产物
  uv run python scripts/generate_protocol.py --check         # 校验产物一致，不一致退出码 1
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

AGENT_DIR = Path(__file__).resolve().parents[1]
_REPO = AGENT_DIR.parent
_MANIFEST = AGENT_DIR / "executor" / "protocol_manifest.yaml"
_OUT_PY = _REPO / "backend" / "app" / "schemas" / "generated_case_params.py"
_OUT_JSON = _REPO / "backend" / "app" / "protocol" / "action_registry.json"
_OUT_TS = _REPO / "frontend" / "src" / "api" / "generated" / "registry.ts"

_HEADER = "# DO NOT EDIT — generated by agent/scripts/generate_protocol.py from agent/executor/protocol_manifest.yaml"


def _load_manifest() -> dict:
    with _MANIFEST.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


# ---------- JSON 产物 ----------


def _build_json(manifest: dict) -> dict:
    return {
        "_generated": {
            "do_not_edit": True,
            "source": "agent/executor/protocol_manifest.yaml",
            "generator": "agent/scripts/generate_protocol.py",
        },
        "protocol_version": manifest["protocol_version"],
        "min_agent_version": manifest["min_agent_version"],
        "controls": manifest.get("controls", {}),
        "actions": manifest["actions"],
        "assertions": manifest["assertions"],
    }


def _render_json(manifest: dict) -> str:
    return json.dumps(_build_json(manifest), ensure_ascii=False, indent=2) + "\n"


# ---------- Python 产物 ----------


_PY_SNIPPET_TYPES = {
    "string": "str",
    "boolean": "bool",
    "integer": "int",
    "number": "float",
    "select": "str",
}

_PY_LITERAL_SNIPPET = """{name}: Literal[{choices}] = {default}


"""


def _py_field_snippet(param: dict) -> str:
    name = param["name"]
    type_ = _PY_SNIPPET_TYPES[param["type"]]
    if param.get("required"):
        return f"    {name}: {type_}\n"
    default = param.get("default")
    if type_ == "str":
        return f"    {name}: {type_} | None = None\n"
    if type_ == "bool":
        return f"    {name}: {type_} = {repr(bool(default)) if default is not None else 'False'}\n"
    kwargs = []
    if "min" in param:
        kwargs.append(f"ge={param['min']}")
    if "max" in param:
        kwargs.append(f"le={param['max']}")
    if default is None:
        default = 0
    if type_ == "float":
        default = float(default)
    default_repr = repr(default)
    if kwargs:
        return f"    {name}: {type_} = Field(default={default_repr}, {', '.join(kwargs)})\n"
    return f"    {name}: {type_} = {default_repr}\n"


def _render_py(manifest: dict) -> str:
    lines = [
        _HEADER,
        "",
        "from typing import Literal",
        "",
        "from pydantic import BaseModel, Field",
        "",
        "",
        "class ParamsBase(BaseModel):",
        '    """协议参数基类：严格校验，未知参数拒绝（Step 4 契约延续）。"""',
        '    model_config = {"extra": "forbid"}',
        "",
    ]
    models: list[str] = []
    for item in [*manifest["actions"], *manifest["assertions"]]:
        cls_name = _cls_name(item["name"])
        models.append(cls_name)
        lines.append(f"class {cls_name}(ParamsBase):")
        if not item["params"]:
            lines.append("    pass")
            lines.append("")
            lines.append("")
            continue
        for param in item["params"]:
            if param["type"] == "select":
                options = [o["value"] for o in param.get("options", [])]
                choices = ", ".join(repr(o) for o in options)
                default = repr(param.get("default") or options[0])
                lines.append(f"    {param['name']}: Literal[{choices}] = {default}")
            else:
                lines.append(_py_field_snippet(param).rstrip())
        lines.append("")
        lines.append("")
    kind = "action" if len(models) <= len(manifest["actions"]) + 1 else "?"
    lines.append("STEP_PARAM_MODELS: dict[str, type[ParamsBase]] = {")
    for item in manifest["actions"]:
        lines.append(f"    {item['name']!r}: {_cls_name(item['name'])},  # noqa: F821")
    lines.append("}")
    lines.append("")
    lines.append("ASSERTION_PARAM_MODELS: dict[str, type[ParamsBase]] = {")
    for item in manifest["assertions"]:
        lines.append(f"    {item['name']!r}: {_cls_name(item['name'])},  # noqa: F821")
    lines.append("}")
    lines.append("")
    lines.append("KNOWN_ACTIONS = frozenset(STEP_PARAM_MODELS)")
    lines.append("KNOWN_ASSERTIONS = frozenset(ASSERTION_PARAM_MODELS)")
    lines.append("")
    lines.append(f"PROTOCOL_VERSION = {manifest['protocol_version']!r}")
    lines.append("")
    if kind == "?":  # never used
        return "\n".join(lines)  # pragma: no cover
    return "\n".join(lines)


def _cls_name(protocol_name: str) -> str:
    return "".join(part.capitalize() for part in protocol_name.split("_")) + "Params"


# ---------- TypeScript 产物 ----------


def _ts_field_type(param: dict) -> str:
    return {
        "string": "'text'",
        "boolean": "'switch'",
        "integer": "'number'",
        "number": "'number'",
        "select": "'select'",
    }[param["type"]]


def _ts_field_snippet(param: dict, indent: str) -> str:
    name = param["name"]
    label = param.get("label", name)
    field_type = _ts_field_type(param)
    extras: list[str] = []
    if "default" in param and param["type"] != "select":
        extras.append(f"default: {json.dumps(param['default'], ensure_ascii=False)}")
    if param.get("required"):
        extras.append("required: true")
    if "min" in param:
        extras.append(f"min: {param['min']}")
    if "max" in param:
        extras.append(f"max: {param['max']}")
    if param.get("placeholder"):
        extras.append(f"placeholder: {json.dumps(param['placeholder'], ensure_ascii=False)}")
    if param["type"] == "select":
        options = ", ".join(
            f"{{ value: {o['value']!r}, label: {o.get('label', o['value'])!r} }}" for o in param.get("options", [])
        )
        extras.append(f"options: [{options}]")
        if "default" in param:
            extras.append(f"default: {param['default']!r}")
    head = f"{indent}{{ key: {name!r}, label: {label!r}, type: {field_type}"
    tail = ", ".join(extras)
    if tail:
        return f"{head}, {tail} }}"
    return f"{head} }}"


def _render_ts(manifest: dict) -> str:
    lines = [
        "// DO NOT EDIT — generated by agent/scripts/generate_protocol.py from agent/executor/protocol_manifest.yaml",
        "",
        "export interface ParamField {",
        "  key: string",
        "  label: string",
        "  type: 'text' | 'number' | 'select' | 'switch'",
        "  options?: { value: string; label: string }[]",
        "  default?: string | number | boolean",
        "  placeholder?: string",
        "  required?: boolean",
        "  min?: number",
        "  max?: number",
        "}",
        "",
        "export interface ActionMeta {",
        "  value: string",
        "  label: string",
        "  needsElement: boolean",
        "  fields: ParamField[]",
        "}",
        "",
        "export interface AssertionMeta {",
        "  value: string",
        "  label: string",
        "  needsElement: boolean",
        "  fields: ParamField[]",
        "}",
        "",
    ]
    lines.append("export const PROTOCOL_VERSION = " + json.dumps(manifest["protocol_version"]) + "")
    lines.append("")
    lines.append("export const ACTIONS: ActionMeta[] = [")
    for item in manifest["actions"]:
        lines.append(f"  {{ value: {item['name']!r}, label: {item['label']!r}, needsElement: {str(item['needs_element']).lower()}, fields: [")
        for param in item["params"]:
            lines.append(_ts_field_snippet(param, "    ") + ",")
        lines.append("  ] },")
    lines.append("]")
    lines.append("")
    lines.append("export const ASSERTION_TYPES: AssertionMeta[] = [")
    for item in manifest["assertions"]:
        lines.append(f"  {{ value: {item['name']!r}, label: {item['label']!r}, needsElement: {str(item['needs_element']).lower()}, fields: [")
        for param in item["params"]:
            lines.append(_ts_field_snippet(param, "    ") + ",")
        lines.append("  ] },")
    lines.append("]")
    return "\n".join(lines) + "\n"


# ---------- 主流程 ----------


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 Protocol Registry 只读产物")
    parser.add_argument("--check", action="store_true", help="校验 tracked 产物与最新 manifest 一致")
    args = parser.parse_args()

    manifest = _load_manifest()
    json_out = _render_json(manifest)
    py_out = _render_py(manifest)
    ts_out = _render_ts(manifest)

    expected = {_OUT_JSON: json_out, _OUT_PY: py_out, _OUT_TS: ts_out}
    stale = [str(path) for path, content in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if stale:
        if args.check:
            print(f"产物过期，请运行 scripts/generate_protocol.py 重新生成: {stale}")
            return 1
        for path in expected:
            _write(path, expected[path])
        print("已生成: " + ", ".join(str(p) for p in expected))
        return 0
    print("全部产物已是最新")
    return 0


if __name__ == "__main__":
    sys.exit(main())
