"""add smart locator check constraints

Revision ID: 28157b8a3f8a
Revises: d62618640a56
Create Date: 2026-08-27 12:04:37.349308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28157b8a3f8a'
down_revision: Union[str, Sequence[str], None] = 'd62618640a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_profile_element_locator_mode', 'app_profile_element_overrides', "(locator_type = 'smart' AND locator_config IS NOT NULL AND locator_value IS NULL) OR (locator_type <> 'smart' AND locator_config IS NULL AND locator_value IS NOT NULL)")
    op.create_check_constraint('ck_test_elements_locator_mode', 'test_elements', "(locator_type = 'smart' AND locator_config IS NOT NULL AND locator_value IS NULL) OR (locator_type <> 'smart' AND locator_config IS NULL AND locator_value IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_test_elements_locator_mode', 'test_elements', type_='check')
    op.drop_constraint('ck_profile_element_locator_mode', 'app_profile_element_overrides', type_='check')
    # ### end Alembic commands ###
