"""add executions stop_requested_at finalized_at

Revision ID: 5f986ae0e6bc
Revises: 87a7005420f3
Create Date: 2026-08-21 14:20:00.460518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f986ae0e6bc'
down_revision: Union[str, Sequence[str], None] = '87a7005420f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('stop_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('executions', sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'finalized_at')
    op.drop_column('executions', 'stop_requested_at')
    # ### end Alembic commands ###
