"""execution_steps 增加 continue_on_failure 快照列

Revision ID: 67bf4a60ab85
Revises: 9c8f570aa059
Create Date: 2026-08-26 15:50:35.972437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bf4a60ab85'
down_revision: Union[str, Sequence[str], None] = '9c8f570aa059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'execution_steps',
        sa.Column('continue_on_failure', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('execution_steps', 'continue_on_failure', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_steps', 'continue_on_failure')
    # ### end Alembic commands ###
