"""add agents deleted_at

Revision ID: 7f33770e371e
Revises: 39809fe557e1
Create Date: 2026-08-22 00:26:52.948202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f33770e371e'
down_revision: Union[str, Sequence[str], None] = '39809fe557e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_agents_deleted_at'), 'agents', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_deleted_at'), table_name='agents')
    op.drop_column('agents', 'deleted_at')
    # ### end Alembic commands ###
