"""test_elements 新增适用范围 scope 列

Revision ID: 862186f0760d
Revises: c7e4a5b30d21
Create Date: 2026-08-27 09:30:01.595649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862186f0760d'
down_revision: Union[str, Sequence[str], None] = 'c7e4a5b30d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 兼容既有行：server_default 'all'（表示所有），随后可在模型侧不再显式默认
    op.add_column(
        'test_elements',
        sa.Column('scope', sa.String(length=100), nullable=False, server_default='all'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_elements', 'scope')
    # ### end Alembic commands ###
