"""add variables scope check + unique indexes

Revision ID: 948d9af2fd30
Revises: a8b728366acf
Create Date: 2026-08-21 11:27:47.766464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948d9af2fd30'
down_revision: Union[str, Sequence[str], None] = 'a8b728366acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_variables_case_name', 'variables', ['case_id', 'name'], unique=True, postgresql_where=sa.text("scope = 'case'"))
    op.create_index('uq_variables_global_name', 'variables', ['name'], unique=True, postgresql_where=sa.text("scope = 'global'"))
    op.create_index('uq_variables_project_name', 'variables', ['project_id', 'name'], unique=True, postgresql_where=sa.text("scope = 'project'"))
    op.create_index('uq_variables_suite_name', 'variables', ['suite_id', 'name'], unique=True, postgresql_where=sa.text("scope = 'suite'"))
    op.create_check_constraint('ck_variables_scope_fk', 'variables', "(scope = 'global' AND project_id IS NULL AND suite_id IS NULL AND case_id IS NULL) OR (scope = 'project' AND project_id IS NOT NULL AND suite_id IS NULL AND case_id IS NULL) OR (scope = 'suite' AND project_id IS NOT NULL AND suite_id IS NOT NULL AND case_id IS NULL) OR (scope = 'case' AND project_id IS NOT NULL AND case_id IS NOT NULL AND suite_id IS NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_variables_scope_fk', 'variables', type_='check')
    op.drop_index('uq_variables_suite_name', table_name='variables', postgresql_where=sa.text("scope = 'suite'"))
    op.drop_index('uq_variables_project_name', table_name='variables', postgresql_where=sa.text("scope = 'project'"))
    op.drop_index('uq_variables_global_name', table_name='variables', postgresql_where=sa.text("scope = 'global'"))
    op.drop_index('uq_variables_case_name', table_name='variables', postgresql_where=sa.text("scope = 'case'"))
    # ### end Alembic commands ###
