"""add executions.session_token

Revision ID: a8b728366acf
Revises: 6a7fb396ae24
Create Date: 2026-08-21 11:12:57.555646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b728366acf'
down_revision: Union[str, Sequence[str], None] = '6a7fb396ae24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('session_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'session_token')
    # ### end Alembic commands ###
