"""add smart locator config

Revision ID: d62618640a56
Revises: 862186f0760d
Create Date: 2026-08-27 11:39:17.615813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62618640a56'
down_revision: Union[str, Sequence[str], None] = '862186f0760d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_profile_element_overrides', sa.Column('locator_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('app_profile_element_overrides', 'locator_value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('ck_profile_element_locator_value'), 'app_profile_element_overrides', type_='check')
    op.add_column('test_elements', sa.Column('locator_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('test_elements', 'locator_value',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_elements', 'locator_value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('test_elements', 'locator_config')
    op.create_check_constraint(op.f('ck_profile_element_locator_value'), 'app_profile_element_overrides', 'length(btrim(locator_value)) > 0')
    op.alter_column('app_profile_element_overrides', 'locator_value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('app_profile_element_overrides', 'locator_config')
    # ### end Alembic commands ###
