"""add app profile tables and execution profile fields

Revision ID: f0cd8a466619
Revises: 38edd56cbeda
Create Date: 2026-08-25 10:47:46.790519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0cd8a466619'
down_revision: Union[str, Sequence[str], None] = '38edd56cbeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inherit_all', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("code ~ '^[a-z][a-z0-9_-]{1,63}$'", name='ck_app_profiles_code'),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_app_profiles_status'),
    sa.CheckConstraint('revision >= 1', name='ck_app_profiles_revision'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_profiles_project_status', 'app_profiles', ['project_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_app_profiles_project_code_active', 'app_profiles', ['project_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_app_profiles_project_name_active', 'app_profiles', ['project_id', sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('app_profile_audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('revision_before', sa.BigInteger(), nullable=False),
    sa.Column('revision_after', sa.BigInteger(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('profile_create', 'profile_update', 'profile_disable', 'release_create', 'release_update', 'release_disable', 'skip_batch', 'restore_batch', 'element_override_upsert', 'element_override_restore', 'variable_override_upsert', 'variable_override_restore', 'node_override_upsert', 'node_override_restore')", name='ck_profile_audit_action'),
    sa.CheckConstraint("jsonb_typeof(changes) = 'array'", name='ck_profile_audit_changes'),
    sa.CheckConstraint('revision_after >= revision_before', name='ck_profile_audit_revisions'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'request_id', name='uq_profile_audit_request')
    )
    op.create_index('idx_profile_audit_actor_time', 'app_profile_audit_logs', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_profile_audit_profile_time', 'app_profile_audit_logs', ['profile_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_profile_audit_project_time', 'app_profile_audit_logs', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('app_profile_element_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('locator_type', sa.String(length=50), nullable=False),
    sa.Column('locator_value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(btrim(locator_value)) > 0', name='ck_profile_element_locator_value'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['test_elements.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_element_override_element', 'app_profile_element_overrides', ['element_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_profile_element_override_active', 'app_profile_element_overrides', ['profile_id', 'element_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('app_profile_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('build_number', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_app_profile_releases_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_profile_releases_profile_status', 'app_profile_releases', ['profile_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_app_profile_releases_version_active', 'app_profile_releases', ['profile_id', 'version', sa.literal_column("COALESCE(build_number, '')")], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('app_profile_variable_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("name ~ '^[A-Za-z_][A-Za-z0-9_]{0,99}$'", name='ck_profile_variable_name'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_profile_variable_override_active', 'app_profile_variable_overrides', ['profile_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('execution_exclusions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('app_profile_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('suite_id_snapshot', sa.Integer(), nullable=True),
    sa.Column('suite_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('case_id_snapshot', sa.Integer(), nullable=True),
    sa.Column('case_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('node_key', sa.Uuid(), nullable=True),
    sa.Column('node_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_rule_id', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.Column('reason_note', sa.String(length=500), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(details) = 'object'", name='ck_execution_exclusion_details'),
    sa.CheckConstraint("source_type IN ('direct', 'inherited', 'empty_after_filter')", name='ck_execution_exclusion_source'),
    sa.CheckConstraint("target_type IN ('suite', 'case', 'step', 'assertion')", name='ck_execution_exclusion_target'),
    sa.ForeignKeyConstraint(['app_profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_exclusions_case', 'execution_exclusions', ['case_id_snapshot'], unique=False, postgresql_where=sa.text('case_id_snapshot IS NOT NULL'))
    op.create_index('idx_execution_exclusions_created_brin', 'execution_exclusions', [sa.literal_column('created_at')], unique=False, postgresql_using='brin')
    op.create_index('idx_execution_exclusions_execution', 'execution_exclusions', ['execution_id', 'target_type'], unique=False)
    op.create_index('idx_execution_exclusions_profile_time', 'execution_exclusions', ['app_profile_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('app_profile_node_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.Uuid(), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("jsonb_typeof(patch) = 'object' AND patch <> '{}'::jsonb", name='ck_profile_node_override_patch'),
    sa.CheckConstraint("target_type IN ('step', 'assertion')", name='ck_profile_node_override_type'),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_node_override_case', 'app_profile_node_overrides', ['case_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_profile_node_override_active', 'app_profile_node_overrides', ['profile_id', 'target_type', 'case_id', 'node_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('app_profile_skip_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('node_key', sa.Uuid(), nullable=True),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.Column('reason_note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(target_type = 'suite' AND suite_id IS NOT NULL AND case_id IS NULL AND node_key IS NULL) OR (target_type = 'case' AND suite_id IS NULL AND case_id IS NOT NULL AND node_key IS NULL) OR (target_type IN ('step', 'assertion') AND suite_id IS NULL AND case_id IS NOT NULL AND node_key IS NOT NULL)", name='ck_profile_skip_target_shape'),
    sa.CheckConstraint("reason_code <> 'other' OR length(btrim(COALESCE(reason_note, ''))) > 0", name='ck_profile_skip_reason_note'),
    sa.CheckConstraint("reason_code IN ('unsupported', 'not_adapted', 'deprecated', 'environment_limit', 'other')", name='ck_profile_skip_reason'),
    sa.CheckConstraint("target_type IN ('suite', 'case', 'step', 'assertion')", name='ck_profile_skip_target_type'),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['app_profiles.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profile_skip_case', 'app_profile_skip_rules', ['case_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_profile_skip_profile_type', 'app_profile_skip_rules', ['profile_id', 'target_type'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_profile_skip_case_active', 'app_profile_skip_rules', ['profile_id', 'case_id'], unique=True, postgresql_where=sa.text("target_type = 'case' AND deleted_at IS NULL"))
    op.create_index('uq_profile_skip_node_active', 'app_profile_skip_rules', ['profile_id', 'target_type', 'case_id', 'node_key'], unique=True, postgresql_where=sa.text("target_type IN ('step', 'assertion') AND deleted_at IS NULL"))
    op.create_index('uq_profile_skip_suite_active', 'app_profile_skip_rules', ['profile_id', 'suite_id'], unique=True, postgresql_where=sa.text("target_type = 'suite' AND deleted_at IS NULL"))
    op.add_column('executions', sa.Column('app_profile_id', sa.Integer(), nullable=True))
    op.add_column('executions', sa.Column('app_profile_name_snapshot', sa.String(length=100), nullable=True))
    op.add_column('executions', sa.Column('app_release_id', sa.Integer(), nullable=True))
    op.add_column('executions', sa.Column('app_release_version_snapshot', sa.String(length=64), nullable=True))
    op.add_column('executions', sa.Column('profile_revision', sa.BigInteger(), nullable=True))
    op.add_column('executions', sa.Column('test_asset_revision', sa.BigInteger(), nullable=True))
    op.add_column('executions', sa.Column('profile_resolution_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_index('idx_executions_profile_created', 'executions', ['app_profile_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_executions_release_created', 'executions', ['app_release_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(None, 'executions', 'app_profile_releases', ['app_release_id'], ['id'])
    op.create_foreign_key(None, 'executions', 'app_profiles', ['app_profile_id'], ['id'])
    op.create_check_constraint('ck_executions_asset_revision', 'executions', 'test_asset_revision IS NULL OR test_asset_revision >= 1')
    op.create_check_constraint('ck_executions_profile_revision', 'executions', 'profile_revision IS NULL OR profile_revision >= 1')
    op.create_check_constraint('ck_executions_resolution_summary', 'executions', "jsonb_typeof(profile_resolution_summary) = 'object'")
    op.add_column('projects', sa.Column('test_asset_revision', sa.BigInteger(), server_default=sa.text('1'), nullable=False))
    op.create_check_constraint('ck_projects_test_asset_revision', 'projects', 'test_asset_revision >= 1')
    op.add_column('reports', sa.Column('not_applicable', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('reports', sa.Column('exclusion_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_check_constraint('ck_reports_exclusion_summary', 'reports', "jsonb_typeof(exclusion_summary) = 'object'")
    op.create_check_constraint('ck_reports_not_applicable', 'reports', 'not_applicable >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_reports_not_applicable', 'reports', type_='check')
    op.drop_constraint('ck_reports_exclusion_summary', 'reports', type_='check')
    op.drop_column('reports', 'exclusion_summary')
    op.drop_column('reports', 'not_applicable')
    op.drop_constraint('ck_projects_test_asset_revision', 'projects', type_='check')
    op.drop_column('projects', 'test_asset_revision')
    op.drop_constraint('ck_executions_resolution_summary', 'executions', type_='check')
    op.drop_constraint('ck_executions_profile_revision', 'executions', type_='check')
    op.drop_constraint('ck_executions_asset_revision', 'executions', type_='check')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_index('idx_executions_release_created', table_name='executions')
    op.drop_index('idx_executions_profile_created', table_name='executions')
    op.drop_column('executions', 'profile_resolution_summary')
    op.drop_column('executions', 'test_asset_revision')
    op.drop_column('executions', 'profile_revision')
    op.drop_column('executions', 'app_release_version_snapshot')
    op.drop_column('executions', 'app_release_id')
    op.drop_column('executions', 'app_profile_name_snapshot')
    op.drop_column('executions', 'app_profile_id')
    op.drop_index('uq_profile_skip_suite_active', table_name='app_profile_skip_rules', postgresql_where=sa.text("target_type = 'suite' AND deleted_at IS NULL"))
    op.drop_index('uq_profile_skip_node_active', table_name='app_profile_skip_rules', postgresql_where=sa.text("target_type IN ('step', 'assertion') AND deleted_at IS NULL"))
    op.drop_index('uq_profile_skip_case_active', table_name='app_profile_skip_rules', postgresql_where=sa.text("target_type = 'case' AND deleted_at IS NULL"))
    op.drop_index('idx_profile_skip_profile_type', table_name='app_profile_skip_rules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_profile_skip_case', table_name='app_profile_skip_rules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('app_profile_skip_rules')
    op.drop_index('uq_profile_node_override_active', table_name='app_profile_node_overrides', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_profile_node_override_case', table_name='app_profile_node_overrides', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('app_profile_node_overrides')
    op.drop_index('idx_execution_exclusions_profile_time', table_name='execution_exclusions')
    op.drop_index('idx_execution_exclusions_execution', table_name='execution_exclusions')
    op.drop_index('idx_execution_exclusions_created_brin', table_name='execution_exclusions', postgresql_using='brin')
    op.drop_index('idx_execution_exclusions_case', table_name='execution_exclusions', postgresql_where=sa.text('case_id_snapshot IS NOT NULL'))
    op.drop_table('execution_exclusions')
    op.drop_index('uq_profile_variable_override_active', table_name='app_profile_variable_overrides', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('app_profile_variable_overrides')
    op.drop_index('uq_app_profile_releases_version_active', table_name='app_profile_releases', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_app_profile_releases_profile_status', table_name='app_profile_releases', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('app_profile_releases')
    op.drop_index('uq_profile_element_override_active', table_name='app_profile_element_overrides', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_profile_element_override_element', table_name='app_profile_element_overrides', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('app_profile_element_overrides')
    op.drop_index('idx_profile_audit_project_time', table_name='app_profile_audit_logs')
    op.drop_index('idx_profile_audit_profile_time', table_name='app_profile_audit_logs')
    op.drop_index('idx_profile_audit_actor_time', table_name='app_profile_audit_logs')
    op.drop_table('app_profile_audit_logs')
    op.drop_index('uq_app_profiles_project_name_active', table_name='app_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_app_profiles_project_code_active', table_name='app_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_app_profiles_project_status', table_name='app_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('app_profiles')
    # ### end Alembic commands ###
