# DO NOT EDIT — generated by agent/scripts/generate_protocol.py from agent/executor/protocol_manifest.yaml

from typing import Literal

from pydantic import BaseModel, Field, model_validator


class ParamsBase(BaseModel):
    """协议参数基类：严格校验，未知参数拒绝（Step 4 契约延续）。"""
    model_config = {"extra": "forbid"}

class LaunchAppParams(ParamsBase):
    package: str
    activity: str | None = None
    no_reset: bool = True


class CloseAppParams(ParamsBase):
    package: str | None = None


class ClickParams(ParamsBase):
    wait_timeout: int = Field(default=10, ge=0, le=300)


class InputParams(ParamsBase):
    value: str
    clear_first: bool = True


class ClearParams(ParamsBase):
    pass


class SwipeParams(ParamsBase):
    direction: Literal['up', 'down', 'left', 'right'] = 'up'
    duration: int = Field(default=500, ge=0)


class SwipeToFindParams(ParamsBase):
    direction: Literal['up', 'down'] = 'up'
    max_swipes: int = Field(default=5, ge=1, le=50)
    wait_timeout: int = Field(default=2, ge=0, le=300)
    duration: int = Field(default=500, ge=0)


class SwipeInElementParams(ParamsBase):
    direction: Literal['up', 'down', 'left', 'right'] = 'up'
    percent: float = Field(default=0.3, ge=0.05, le=0.95)
    wait_timeout: int = Field(default=10, ge=0, le=300)


class SwipeInRegionParams(ParamsBase):
    left_percent: float = Field(..., ge=0, le=100)
    top_percent: float = Field(..., ge=0, le=100)
    width_percent: float = Field(..., ge=0.01, le=100)
    height_percent: float = Field(..., ge=0.01, le=100)
    direction: Literal['up', 'down', 'left', 'right'] = 'up'
    percent: float = Field(default=0.3, ge=0.05, le=0.95)

    @model_validator(mode="after")
    def _validate_percent_region(self):
        if self.left_percent + self.width_percent > 100:
            raise ValueError("left_percent + width_percent 不能大于 100")
        if self.top_percent + self.height_percent > 100:
            raise ValueError("top_percent + height_percent 不能大于 100")
        return self


class SwipeInElementFindTextClickParams(ParamsBase):
    target_text: str = Field(..., min_length=1)
    match_mode: Literal['equals', 'contains'] = 'equals'
    preferred_direction: Literal['up', 'down'] = 'up'
    max_swipes_per_direction: int = Field(default=8, ge=1, le=50)
    percent: float = Field(default=0.3, ge=0.05, le=0.95)
    container_wait_timeout: int = Field(default=10, ge=0, le=60)
    settle_ms: int = Field(default=300, ge=0, le=2000)


class ScrollParams(ParamsBase):
    pass


class BackParams(ParamsBase):
    pass


class SleepParams(ParamsBase):
    duration: float = Field(default=1.0, ge=0)


class ScreenshotParams(ParamsBase):
    filename: str | None = None


class GetTextParams(ParamsBase):
    variable_name: str | None = None


class GetAttributeParams(ParamsBase):
    attribute: str
    variable_name: str | None = None


class TapCoordinateParams(ParamsBase):
    x: int
    y: int


class ElementExistsParams(ParamsBase):
    expected: Literal['exists', 'not_exists'] = 'exists'


class TextEqualsParams(ParamsBase):
    expected: str
    trim: bool = False


class TextContainsParams(ParamsBase):
    expected: str


class TextNotContainsParams(ParamsBase):
    expected: str


class AttributeEqualsParams(ParamsBase):
    attribute: str
    expected: str


class AttributeContainsParams(ParamsBase):
    attribute: str
    expected: str


class ValueEqualsParams(ParamsBase):
    expected: str


class RegexMatchParams(ParamsBase):
    pattern: str


STEP_PARAM_MODELS: dict[str, type[ParamsBase]] = {
    'launch_app': LaunchAppParams,  # noqa: F821
    'close_app': CloseAppParams,  # noqa: F821
    'click': ClickParams,  # noqa: F821
    'input': InputParams,  # noqa: F821
    'clear': ClearParams,  # noqa: F821
    'swipe': SwipeParams,  # noqa: F821
    'swipe_to_find': SwipeToFindParams,  # noqa: F821
    'swipe_in_element': SwipeInElementParams,  # noqa: F821
    'swipe_in_region': SwipeInRegionParams,  # noqa: F821
    'swipe_in_element_find_text_click': SwipeInElementFindTextClickParams,  # noqa: F821
    'scroll': ScrollParams,  # noqa: F821
    'back': BackParams,  # noqa: F821
    'sleep': SleepParams,  # noqa: F821
    'screenshot': ScreenshotParams,  # noqa: F821
    'get_text': GetTextParams,  # noqa: F821
    'get_attribute': GetAttributeParams,  # noqa: F821
    'tap_coordinate': TapCoordinateParams,  # noqa: F821
}

ASSERTION_PARAM_MODELS: dict[str, type[ParamsBase]] = {
    'element_exists': ElementExistsParams,  # noqa: F821
    'text_equals': TextEqualsParams,  # noqa: F821
    'text_contains': TextContainsParams,  # noqa: F821
    'text_not_contains': TextNotContainsParams,  # noqa: F821
    'attribute_equals': AttributeEqualsParams,  # noqa: F821
    'attribute_contains': AttributeContainsParams,  # noqa: F821
    'value_equals': ValueEqualsParams,  # noqa: F821
    'regex_match': RegexMatchParams,  # noqa: F821
}

KNOWN_ACTIONS = frozenset(STEP_PARAM_MODELS)
KNOWN_ASSERTIONS = frozenset(ASSERTION_PARAM_MODELS)

PROTOCOL_VERSION = '3.0.0'

STEP_NEEDS_ELEMENT = frozenset({
    'click',
    'input',
    'clear',
    'swipe_to_find',
    'swipe_in_element',
    'swipe_in_element_find_text_click',
    'scroll',
    'get_text',
    'get_attribute',
})

ASSERTION_NEEDS_ELEMENT = frozenset({
    'element_exists',
    'text_equals',
    'text_contains',
    'text_not_contains',
    'attribute_equals',
    'attribute_contains',
    'value_equals',
    'regex_match',
})

ELEMENT_LABELS: dict[str, str] = {
    'swipe_in_element_find_text_click': '列表控件',
}
